# -*- coding: utf-8 -*-
"""strings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQ-M-dSpv9URTCNZpmbEAY-MVIOfkgGU
"""

## Create a program that reads test scores from a CSV file and calculates each student's test average
#open the file and read all lines
with open('test_scores.csv', 'r') as file:
    lines = file.readlines()

#initialize a count
student = 1

#loop through each line to process the scores
for line in lines:
    #strip and convert scores to int
    scores = [int(score) for score in line.strip().split(',')]

    #calculate the total and average
    total = sum(scores)
    average = total / len(scores)

    #print the results for the current student
    print(scores)
    print(f"Total: {total}")
    print(f"Average: {average:.1f}\n")

    #increment the student number
    student += 1

## Create a program that searches for a specific title of a book, if found, prints the associated author's name
#the list of lists
list_of_titles = [['Windtalker','Jones'],['Godfather','Smith'],['Winds of War','Brown']]

#input the title to search
search = input('Enter the title of the book to search: ')

#check if the title matches the search term, if a match is found, print the author name
#boolean variable to track if title found or not
found = False
#for loop to iterate the lists in the list
for title in list_of_titles:
  if title[0] == search:
    author = title[1]
    print(f'The author of {search} is {author}')
    found = True
    break

#if search is not found
if not found:
  print(f'Title {search} is not in the list')